/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrayerTrackerRouteImport } from './routes/prayer-tracker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalCompleteStatisticRouteImport } from './routes/journal/complete-statistic'
import { Route as JournalDailyJournalIndexRouteImport } from './routes/journal/daily-journal/index'
import { Route as JournalDailyJournalCreateRouteImport } from './routes/journal/daily-journal/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as JournalDailyJournalThemeIdRouteImport } from './routes/journal/daily-journal/theme.$id'
import { Route as JournalDailyJournalCreateStepRouteImport } from './routes/journal/daily-journal/create.$step'

const PrayerTrackerRoute = PrayerTrackerRouteImport.update({
  id: '/prayer-tracker',
  path: '/prayer-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalCompleteStatisticRoute =
  JournalCompleteStatisticRouteImport.update({
    id: '/journal/complete-statistic',
    path: '/journal/complete-statistic',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalDailyJournalIndexRoute =
  JournalDailyJournalIndexRouteImport.update({
    id: '/journal/daily-journal/',
    path: '/journal/daily-journal/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalDailyJournalCreateRoute =
  JournalDailyJournalCreateRouteImport.update({
    id: '/journal/daily-journal/create',
    path: '/journal/daily-journal/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalDailyJournalThemeIdRoute =
  JournalDailyJournalThemeIdRouteImport.update({
    id: '/journal/daily-journal/theme/$id',
    path: '/journal/daily-journal/theme/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalDailyJournalCreateStepRoute =
  JournalDailyJournalCreateStepRouteImport.update({
    id: '/$step',
    path: '/$step',
    getParentRoute: () => JournalDailyJournalCreateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/journal/complete-statistic': typeof JournalCompleteStatisticRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/daily-journal/create': typeof JournalDailyJournalCreateRouteWithChildren
  '/journal/daily-journal/': typeof JournalDailyJournalIndexRoute
  '/journal/daily-journal/create/$step': typeof JournalDailyJournalCreateStepRoute
  '/journal/daily-journal/theme/$id': typeof JournalDailyJournalThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/journal/complete-statistic': typeof JournalCompleteStatisticRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/daily-journal/create': typeof JournalDailyJournalCreateRouteWithChildren
  '/journal/daily-journal': typeof JournalDailyJournalIndexRoute
  '/journal/daily-journal/create/$step': typeof JournalDailyJournalCreateStepRoute
  '/journal/daily-journal/theme/$id': typeof JournalDailyJournalThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/journal/complete-statistic': typeof JournalCompleteStatisticRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/daily-journal/create': typeof JournalDailyJournalCreateRouteWithChildren
  '/journal/daily-journal/': typeof JournalDailyJournalIndexRoute
  '/journal/daily-journal/create/$step': typeof JournalDailyJournalCreateStepRoute
  '/journal/daily-journal/theme/$id': typeof JournalDailyJournalThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prayer-tracker'
    | '/journal/complete-statistic'
    | '/api/auth/$'
    | '/journal/daily-journal/create'
    | '/journal/daily-journal/'
    | '/journal/daily-journal/create/$step'
    | '/journal/daily-journal/theme/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prayer-tracker'
    | '/journal/complete-statistic'
    | '/api/auth/$'
    | '/journal/daily-journal/create'
    | '/journal/daily-journal'
    | '/journal/daily-journal/create/$step'
    | '/journal/daily-journal/theme/$id'
  id:
    | '__root__'
    | '/'
    | '/prayer-tracker'
    | '/journal/complete-statistic'
    | '/api/auth/$'
    | '/journal/daily-journal/create'
    | '/journal/daily-journal/'
    | '/journal/daily-journal/create/$step'
    | '/journal/daily-journal/theme/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrayerTrackerRoute: typeof PrayerTrackerRoute
  JournalCompleteStatisticRoute: typeof JournalCompleteStatisticRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  JournalDailyJournalCreateRoute: typeof JournalDailyJournalCreateRouteWithChildren
  JournalDailyJournalIndexRoute: typeof JournalDailyJournalIndexRoute
  JournalDailyJournalThemeIdRoute: typeof JournalDailyJournalThemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prayer-tracker': {
      id: '/prayer-tracker'
      path: '/prayer-tracker'
      fullPath: '/prayer-tracker'
      preLoaderRoute: typeof PrayerTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/complete-statistic': {
      id: '/journal/complete-statistic'
      path: '/journal/complete-statistic'
      fullPath: '/journal/complete-statistic'
      preLoaderRoute: typeof JournalCompleteStatisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/': {
      id: '/journal/daily-journal/'
      path: '/journal/daily-journal'
      fullPath: '/journal/daily-journal/'
      preLoaderRoute: typeof JournalDailyJournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/create': {
      id: '/journal/daily-journal/create'
      path: '/journal/daily-journal/create'
      fullPath: '/journal/daily-journal/create'
      preLoaderRoute: typeof JournalDailyJournalCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/theme/$id': {
      id: '/journal/daily-journal/theme/$id'
      path: '/journal/daily-journal/theme/$id'
      fullPath: '/journal/daily-journal/theme/$id'
      preLoaderRoute: typeof JournalDailyJournalThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/daily-journal/create/$step': {
      id: '/journal/daily-journal/create/$step'
      path: '/$step'
      fullPath: '/journal/daily-journal/create/$step'
      preLoaderRoute: typeof JournalDailyJournalCreateStepRouteImport
      parentRoute: typeof JournalDailyJournalCreateRoute
    }
  }
}

interface JournalDailyJournalCreateRouteChildren {
  JournalDailyJournalCreateStepRoute: typeof JournalDailyJournalCreateStepRoute
}

const JournalDailyJournalCreateRouteChildren: JournalDailyJournalCreateRouteChildren =
  {
    JournalDailyJournalCreateStepRoute: JournalDailyJournalCreateStepRoute,
  }

const JournalDailyJournalCreateRouteWithChildren =
  JournalDailyJournalCreateRoute._addFileChildren(
    JournalDailyJournalCreateRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrayerTrackerRoute: PrayerTrackerRoute,
  JournalCompleteStatisticRoute: JournalCompleteStatisticRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  JournalDailyJournalCreateRoute: JournalDailyJournalCreateRouteWithChildren,
  JournalDailyJournalIndexRoute: JournalDailyJournalIndexRoute,
  JournalDailyJournalThemeIdRoute: JournalDailyJournalThemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
